name: CI

on:
  push:

jobs:
  lean_zx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: zx_view_widget/package.json
          cache: npm
          cache-dependency-path: zx_view_widget/package-lock.json
      - uses: leanprover/lean-action@v1
      - name: Run tests
        run: lake build Tests

      - name: Build demos
        run: lake build Demos

  zx_view_widget:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zx_view_widget

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: zx_view_widget/package.json
          cache: npm
          cache-dependency-path: zx_view_widget/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
